### PR TITLE
wgsl: remove [[block]] and [[strides]], elseif -> else if, [[]] -> @

### PR DESCRIPTION
**Pull request by munrocket**
According to relatively new changes in wgsl.

### CODE REVIEW

**Comment by austinEng** [comment]
I'd like to do our best to keep this working in Chrome Stable, where the [[block]] attribute hasn't been deprecated yet. Will need to wait a bit to land this.

**Comment by HypnosNova** [comment]
And "[[attribute]]" code grammma is changed into "@attribute" style.

**Comment by munrocket** [comment]
Yea, I should add “@“ symbols also.

**Comment by munrocket** [comment]
Updated according to #163 commit, because it seems right.
Also feel free to close PR if it become outdated.

**Comment by webglzhang** [comment]
> 

It's right. I refer to the latest wgsl documentation and run each demo. There are no wgsl related warnings in the demo.

**Comment by webglzhang** [comment]
> Updated according to #163 commit, because it seems right. Also feel free to close PR if it become outdated.

@austinEng @munrocket

**Review by austinEng — APPROVED** [review]
thank you!

**Pull request merged**
