### PR TITLE
Two new cube samples

### PR DESCRIPTION
**Pull request by shrekshao**
Some trivial attempts I made during learning WebGPU

Screen Shot 2019-09-27 at 2 24 41 PM
Screen Shot 2019-09-27 at 2 25 01 PM

### CODE REVIEW

**Comment by austinEng** [comment]
Awesome! Thanks Shrek. The instancing one is a great example! Is the two_cubes sample significantly different from other simple cube example? It looks roughly the same except we have two model matrices and draw it twice. I think we only need to add the instanced example.

**Comment by shrekshao** [comment]
I think the two_cubes sample mainly demonstrate scenario using more than one uniformBindGroups (instanced only have one). 

The offset has to be 256byte aligned https://github.com/austinEng/webgpu-samples/pull/14/files#diff-8edc081d107d2dce08f854f495cb164bR240

I consider it helpful as in GL I usually have 1 uniform matrix and call uniform4fv to reset the same uniform between two drawcall, while here you cannot setSubData for the same variable between recording of drawcall.

**Comment by austinEng** [comment]
Ah, that makes sense that it shows a significant difference between uploading data in WebGPU and WebGL. Thanks!

**Comment by shrekshao** [comment]
Maybe I should archive this https://github.com/austinEng/webgpu-samples/pull/14#issuecomment-537287005 and add this description to readme in the future. Thanks for reviewing.

**Pull request merged**
