### PR TITLE
WebGPU API update and WGSL update

### PR DESCRIPTION
**Pull request by onsummer**
Includes:

## WebGPU API update

- Change `context.getPreferredFormat(adapter)` to `navigator.gpu.getPreferredCanvasFormat()`
- Remove the deprecated `size` in `GPUCanvasConfiguration`, and explicit set `alphaMode` in `GPUCanvasConfiguration`
- Add the required `layout` field for `GPUPipelineDescriptorBase` (both `GPURenderPipeline` and `GPUComputePipeline`
- Change `GPUComputePassEncoder.dispatch` to `GPUComputePassEncoder.dispatchWorkgroups` during passes encoding

## WGSL update

- Using `@vertex`, `@fragment`, `@compute` instead of `@stage(vertex)`, `@stage(fragment)` and `@stage(compute)`
- Change the `;` at the end of the member field in the struct declaration to `,`
- Remove the unnecessary `;` at the end of struct declaration
- Using compound assignment
- Beautify WGSL code indentation

## Other

- Replace `substring` with `substr` in all `makeSample` functions call.
- Add an icon for this pages

---

Looks all samples run well with Chrome Canary 105.0.5165.0

### CODE REVIEW

**Review by austinEng — APPROVED** [review]
Thank you for the updates! Looks great to me, but please take a look at the lint failures. I just approved the CI for this PR.

**Comment by onsummer** [comment]
@austinEng Please take a look, fixed the errors.

**Review by austinEng — APPROVED** [review]

**Comment by onsummer** [comment]
Oh god, what happen...

**Review by austinEng — COMMENTED** [review]
Hm, to make this easier to land, why don't we split it into multiple PRs?
- one for the WGSL changes,
- one for layout: 'auto', etc.

hopefully with smaller changes there will be less issues with the formatter - or it will be more obvious what linting needs to get resolved.

**Pull request closed without merging**
